### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by godleader** [snakeying/GPT-Telegram-Bot#3]
要不要考虑添加一下商业bot 功能

**Comment by snakeying** [comment]
暂无商业打算

**Comment by godleader** [comment]
不是商业，是tg 的吧business api

**Comment by snakeying** [comment]
抱歉？我不太明白你的意思？

**Comment by godleader** [comment]
telegram 不是已经有了新的api 吗？ telegram business ，telegram business
支持把机器人放在个人账号里代替自己回复客户 继承了ai 的话那就相当于把自己的账号变成了ai

**Comment by godleader** [comment]
你的飞机是啥

**Comment by godleader** [comment]
然后目前你的代码， gpt 机器人， 仅仅只是bot 而已，所以我才问你要不要打算开发成telegram business 的api 机器人

**Comment by godleader** [comment]
这样gpt 机器人就可以代替你来回复客户了

**Comment by godleader** [comment]
只是看到你的代码简洁，是我喜欢的那种，所以就信息问你一声...
